### ISSUE TITLE
Error: panic: unknown_method

### ISSUE THREAD

**Issue by KenjiOhtsuka** [joefitzgerald/slack-dump#12]
I tried to use it on Windows 11 but I got the following error.

```
>slack-dump.exe -o dump -t xoxp-XXXXXXXXXXXXXXXXXXXXXXXXXX
dump user information
dump direct message
dump public channel
panic: unknown_method

goroutine 1 [running]:
main.check(0x81a760, 0xc04211c230)
        /home/yossy/.gvm/pkgsets/go1.10.1/global/src/github.com/PyYoshi/slack-dump/main.go:26 +0x51
main.dumpChannels(0xc0421080c0, 0xc042162cc0, 0x35, 0xc0420160d0, 0x0, 0x3, 0x0, 0x14, 0xc042133c40)
        /home/yossy/.gvm/pkgsets/go1.10.1/global/src/github.com/PyYoshi/slack-dump/main.go:241 +0x85
main.dumpRooms(0xc0421080c0, 0xc042162cc0, 0x35, 0xc0420160d0, 0x0, 0x3)
        /home/yossy/.gvm/pkgsets/go1.10.1/global/src/github.com/PyYoshi/slack-dump/main.go:205 +0xd7
main.main.func1(0xc0420b69a0)
        /home/yossy/.gvm/pkgsets/go1.10.1/global/src/github.com/PyYoshi/slack-dump/main.go:100 +0x227
github.com/PyYoshi/slack-dump/vendor/github.com/urfave/cli.HandleAction(0x7485e0, 0x7ee470, 0xc0420b69a0, 0xc04205a4e0, 0x0)
        /home/yossy/.gvm/pkgsets/go1.10.1/global/src/github.com/PyYoshi/slack-dump/vendor/github.com/urfave/cli/app.go:503 +0x83
github.com/PyYoshi/slack-dump/vendor/github.com/urfave/cli.(*App).Run(0xc04210e000, 0xc042016080, 0x5, 0x8, 0x0, 0x0)
        /home/yossy/.gvm/pkgsets/go1.10.1/global/src/github.com/PyYoshi/slack-dump/vendor/github.com/urfave/cli/app.go:268 +0x613
main.main()
        /home/yossy/.gvm/pkgsets/go1.10.1/global/src/github.com/PyYoshi/slack-dump/main.go:105 +0x330
```

```
>go version
go version go1.18 windows/amd64
```

```
>slack-dump.exe -v
slack-dump version 1.1.3
```

Is there someone who can tell me how can I solve this? Thanks in advance.

**Comment by KenjiOhtsuka** [comment]
Sorry, I had to post other repository.

and this version https://github.com/takameron/slack-dump/releases worked.
